[FIX] connector_magento: register components only once in savepoint case
```
 ERROR: test_import_images_403 (odoo.addons.connector_magento.tests.test_import_product_image.TestImportProductImage)
 ` Import a product when an image respond a 403 error, should fail
 Traceback (most recent call last):
 `   File "/home/odoo/connector-magento/connector_magento/tests/test_import_product_image.py", line 91, in setUp
 `     self._build_components(StubProductAdapter,
 `   File "/home/odoo/connector/component/tests/common.py", line 204, in _build_components
 `     cls._build_component(self.comp_registry)
 `   File "/home/odoo/connector/component/core.py", line 828, in _build_component
 `     raise TypeError('Component %r (in class %r) already exists. '
 ` TypeError: Component 'stub.product.adapter' (in class <class 'odoo.addons.connector_magento.tests.test_import_product_image.TestImportProductImage.setUp.<locals>.StubProductAdapter'>) already exists. Consider using _inherit instead of _name or using a different _name.
```